### ISSUE TITLE
Posting JSON broken on Dataverse 5.9

### ISSUE THREAD

**Issue by Jeija** [gdcc/pyDataverse#143] opened 2022-03-02 09:47 UTC
Creating a new dataset does not work anymore with Dataverse 5.9:
```
>>> resp = api.create_dataset("my_dataverse_name", json.dumps({"datasetVersion": dataset_description}))
```
with some valid `dataset_description` object returns
```
>>> resp.json()
{'status': 'ERROR', 'message': 'Validation Failed: Author Name is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Contact E-mail is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Description Text is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Subject is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Title is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]).'}
```

The same code worked for older Dataverse versions.

For some reason, Dataverse now needs a `Content-Type: application/json` header to understand my JSON.
I have been able to fix this issue temporarily by replacing [this line](https://github.com/gdcc/pyDataverse/blob/master/src/pyDataverse/api.py#L174) in `post_request` with
```
headers = {}
headers["Content-Type"] = "application/json"
resp = post(url, data=data, params=params, files=files, headers=headers)
```
but I don't think that's the proper way to do it (may cause issues when posting files).

**Comment by pdurbin** [comment] 2022-03-22 18:56
@Jeija my guess is that the change (enforcement of Author Name and other required fields) occurred with Dataverse 5.7. I left a comment about this here: https://github.com/IQSS/dataverse/issues/8210#issuecomment-1064392959

**Comment by Jeija** [comment] 2022-03-22 21:16
Thanks for digging into this. I also just wanted to mention that there is a patch for pyDataverse that should fix this issue out there now: https://github.com/JR-1991/pyDataverse/commit/0fcfcd3fbc6bf1aec869899f715a51dca25e91be
(I haven't tested it or looked into it more closely at this point)

**Comment by pdurbin** [comment] 2022-04-28 14:05
@Jeija interesting. We're discussing the content type header here (please feel free to join in):

- https://github.com/IQSS/dataverse.harvard.edu/issues/155

**Comment by jggautier** [comment] 2022-07-21 16:53
A depositor I was helping might've run into this issue when using the create_dataset function. Until the function is updated, I thought it would be helpful to share a workaround.

After reading in the dataset.json file (the one at https://github.com/gdcc/pyDataverse/blob/master/tests/data/user-guide/dataset.json) as a string, if I do a json.loads, then json.dumps, then pass that variable into the create_dataset function, the dataset is created. I tested this a few times on the Harvard repository:

```
with open(path_to_json_file, 'r') as f:
    ds = f.read()
    ds = json.loads(ds)
    ds = json.dumps(ds)

resp = api.create_dataset('dataverse_alias', ds)
```

**Comment by pdurbin** [comment] 2022-07-21 20:47
@jggautier interesting fix. Maybe at that point Python knows it's JSON instead of a string and sends the application/json content type header?

Anyway, hopefully #145 will fix it.

Also, in https://github.com/IQSS/dataverse/pull/8676 we updated the API Guide to say that the application/json content type header is now required to create a dataset.

**Comment by skasberger** [comment] 2022-08-27 08:48
Update: I left AUSSDA, so my funding for pyDataverse development has stopped. 

I want to get some basic funding to implement the most urgent updates (PRs, Bug fixes, maintenance work). If you can support this, please reach out to me. (www.stefankasberger.at). If you have feature requests, the same.

Another option would be, that someone else helps with the development and / or maintenance. For this, also get in touch with me (or comment here).

**Comment by jmurugan-fzj** [comment] 2023-11-22 16:04
@pdurbin I have seen the same problem in the latest pydataverse version, while creating datasets in [local data-verse setup](https://github.com/IQSS/dataverse-docker), invoking the api.create_dataset fails with the validation error and the same error can be also reproduced in the postman easily by simply not setting the 'Content-Type' in the headers. I guess, missing 'Content-Type' leads to the server behavior that it fails to parse 'metadatablock' in the request body...

![image](https://github.com/gdcc/pyDataverse/assets/141253011/2fa970d4-3e51-4b47-9d10-73f16e024cd5)


![image](https://github.com/gdcc/pyDataverse/assets/141253011/d5d1f10c-37fa-42ff-bc1f-bbcbfd7f67b5)

Where as the demo.dataverse.org does not seem to have this problem, it works even without 'Content-Type' in the headers, is this some API level setting in demo.dataverse.org which makes it behave differently or could be software version difference? Just being curious...!

![image](https://github.com/gdcc/pyDataverse/assets/141253011/0a2d8684-3c6b-4fc9-af9c-bb6cd8d58a13)

**Comment by pdurbin** [comment] 2023-11-28 19:06
@jmurugan-fzj yes, this is expected because the following pull request (or equivalent) hasn't been merged yet:

- #145

Th backward incompatibility isn't pyDataverse's fault. It was introduced upstream in https://github.com/IQSS/dataverse/commit/509746ca6091858a1ae9a8786f8a0e634d10c9d0 in 2021 (v5.6).

The demo server should be the same as your local env. I'm not sure why you're seeing a difference. 🤔

**Comment by jmurugan-fzj** [comment] 2023-11-29 09:46
> @jmurugan-fzj yes, this is expected because the following pull request (or equivalent) hasn't been merged yet:
> 
> * [fix newer dataverse compatibility by adding content-type=application/json header #145](https://github.com/gdcc/pyDataverse/pull/145)
> 
> Th backward incompatibility isn't pyDataverse's fault. It was introduced upstream in [IQSS/dataverse@509746c](https://github.com/IQSS/dataverse/commit/509746ca6091858a1ae9a8786f8a0e634d10c9d0) in 2021 (v5.6).
> 
> The demo server should be the same as your local env. I'm not sure why you're seeing a difference. 🤔

@pdurbin The default installation of [dataverse-docker](https://github.com/IQSS/dataverse-docker) spins up an old version of data-verse container (coronawhy/dataverse: 5.13.allclouds), this was the reason for the validation error, once I updated docker-compose to use the latest version, this error does not occur anymore!

**Comment by pdurbin** [comment] 2023-11-29 15:26
@jmurugan-fzj great! When you say latest 6.0 container, are you talking about the alpha image from https://hub.docker.com/r/gdcc/dataverse ? If you'd ever like to talk containers, we have a weekly meeting: https://ct.gdcc.io

**Comment by pdurbin** [comment] 2024-05-10 11:17
> The backward incompatibility isn't pyDataverse's fault. It was introduced upstream in [IQSS/dataverse@509746c](https://github.com/IQSS/dataverse/commit/509746ca6091858a1ae9a8786f8a0e634d10c9d0) in 2021 (v5.6).

We documented this in our new API changelog of breaking changes:

- https://github.com/IQSS/dataverse/pull/10467

**Comment by JR-1991** [comment] 2024-05-10 12:21
@Jeija thanks for submitting this issue. We have resolved this with the switch to `httpx` and the latest commit https://github.com/gdcc/pyDataverse/commit/929e5c949589909ebcf8d50de194de5573869d9a. As shown in the attached screenshot, POST and PUT requests now send the correct header upon dispatch.

<img width="1840" alt="image" src="https://github.com/gdcc/pyDataverse/assets/30547301/b6d01b89-06ec-49a4-87c4-68d6aa4d771a">

**Closed by JR-1991** 2024-05-10 12:21 UTC
Labels: type:bug, status:incoming
